on:
  workflow_dispatch:
    

name: debug-action

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ticket-regex: '/EDT-\d+/'
          jira-host: https://support.chili-publish.com/
          jira-username:  ${{ secrets.JIRA_USER }}
          jira-password:  ${{ secrets.JIRA_PASSWD }}